config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admins
  devise_for :users
  root to: 'pages#home'
  get 'auth/callback', to: 'companies#auth_callback'
  get 'apis', to: 'pages#apis'
  resources :companies do
    member do
      post :provision
      get :auth_callback
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  def application
    OauthApplication.find_by(id: self.application_id)
  end
end

app/models/oauth_access_token.rb
class OauthAccessToken < ApplicationRecord
end

app/models/oauth_application.rb
class OauthApplication < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :access_grants,
         class_name: 'Doorkeeper::AccessGrant',
         foreign_key: :resource_owner_id,
         dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens,
         class_name: 'Doorkeeper::AccessToken',
         foreign_key: :resource_owner_id,
         dependent: :delete_all # or :destroy if you need callbacks

  belongs_to :company, optional: true
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :doorkeeper_authorize!

  def index
    render json: company.users
  end

  private

  def current_user
    @current_user ||= User.find_by(id: doorkeeper_token.resource_owner_id)
  end

  def company
    @company ||= current_user.company
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!, only: %i[provision auth_callback]
  before_action :authenticate_admin!, except: %i[provision auth_callback]
  before_action :set_company, only: %i[ show edit update destroy provision auth_callback]

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
   
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save

        app = Doorkeeper::Application.create(name: "#{@company.name}-#{@company.id}", redirect_uri: auth_callback_company_url(@company), scopes: ["public"])
        @company.update_column(:application_id, app.id)

        format.html { redirect_to companies_path, notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def provision
    user = User.find_by(id: params[:user_id])
    callback = auth_callback_company_url(@company)
    app_id = @company.application[:uid]
    secret = @company.application[:secret]
    client = OAuth2::Client.new(app_id, secret, site: root_url)
    authorize_url = client.auth_code.authorize_url(redirect_uri: callback)
    redirect_to authorize_url
  end

  def auth_callback
    callback = auth_callback_company_url(@company)
    # byebug
    app_id = @company.application[:uid]
    secret = @company.application[:secret]
    client = OAuth2::Client.new(app_id, secret, site: root_url)
    
    Spawnling.new do
      access = client.auth_code.get_token(params[:code], redirect_uri: callback)

      current_user.access_token = access.token
      current_user.company_id = @company.id
      current_user.save
    end
    redirect_to apis_url, notice: "Successfully provision to #{@company.name}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @companies = Company.all
  end
  def apis
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>App ID</th>
      <th>App Secret</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.application.try(:uid) %></td>
        <td><%= company.application.try(:secret) %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TypfoomAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <hr>
    <% if user_signed_in? %>
     <span>Welcome user <%= current_user.email %></span>
     <%= link_to "Logout", destroy_user_session_path, method: :delete%>
    <% else %>
     <%= link_to "Login as user", new_user_session_path if !current_admin %>
    <% end %>

    <% if admin_signed_in? %>
      <span>Welcome Admin | </span>
     <%= link_to "Logout", destroy_admin_session_path, method: :delete%>
    <% else %>
     <%= link_to "Login as admin", new_admin_session_path if !current_user %>
    <% end %>
  </body>
</html>

app/views/pages/apis.html.erb
<%= link_to "#{current_user.company.try(:name)} USERS LIST", api_v1_users_path(access_token: current_user.access_token), target: '_blank' %>

app/views/pages/home.html.erb
<% if admin_signed_in? %>
<%= link_to 'Go to companies', companies_path %>
<% end %>

<% if user_signed_in? %>
<table>
  <thead>
    <tr>
      <th>Company Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td>
          <% if !current_user.access_token.present? || current_user.company_id != company.id %>
            <%= link_to 'Provision', provision_company_path(company, user_id: current_user.id), method: :post, data: { turbolinks: false } %> 
          <% else %>
            PROVISIONED
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>